/* GENERATED from flow_edge_semantics.json by gen_flow_edge_semantics.mjs.
   file:// loader shim: fetch() is blocked on the file scheme, so the flow
   tab reads this global. Keep in sync via the generator — do not hand-edit. */
window.__FLOW_EDGE_SEMANTICS__ = {
  "_comment": "GENERATED by tools/theses/dashboard/ui/gen_flow_edge_semantics.mjs — do not hand-edit. Glyph vocabulary is derived from src/engine/contracts/binary_layouts.ts (LAW 7); measured edges are transcribed from the Arrow serialization-walls report.",
  "generated_at": "2026-07-11T15:37:22.275Z",
  "provenance": {
    "glyph_vocabulary_source": {
      "file": "src/engine/contracts/binary_layouts.ts",
      "schema_version": "0.2.0",
      "law": "LAW 7 (Memory Boundary Layout) — glyphs are keyed to enumerated boundaries"
    },
    "measured_edges_source": {
      "path": "test_results/arrow_serialization_walls_2026-07-11/measurements.json",
      "date": "2026-07-11",
      "repo_head": "912fb68 (main)",
      "note": "Walls 1-3 carry MEASURED transfer semantics (buffer identity + N=5 median memcpy/clone/transfer timings). Wall 4 (Tauri IPC) is STATIC inventory only — runtime NOT MEASURED (needs the packaged desktop app). Edges off wall 4 render grey."
    }
  },
  "viewbox": {
    "w": 948,
    "h": 400
  },
  "line_classes": [
    {
      "id": "shared_view",
      "label": "zero-copy — SHARED VIEW",
      "dash": "dotted",
      "color": "view",
      "meaning": "Same ArrayBuffer, wrapped in place. No bytes move; a validity bitmap or header is the only overhead."
    },
    {
      "id": "ownership_transfer",
      "label": "zero-copy — OWNERSHIP TRANSFER",
      "dash": "dot-dash",
      "color": "transfer",
      "meaning": "Transferable: the buffer is detached from the sender and handed to the receiver. The measured 172-482x lever — semantically distinct from a shared view (sender loses access)."
    },
    {
      "id": "copy",
      "label": "COPY / SERIALIZE",
      "dash": "solid",
      "color": "copy",
      "meaning": "Bytes are duplicated (memcpy) or serialized (structuredClone / JSON). Stroke weight is proportional to the measured cost in ms."
    }
  ],
  "glyph_vocabulary": [
    {
      "id": "typed_u16",
      "shape": "square",
      "label": "u16 typed array",
      "schema_entry": "libraw_mem_image",
      "schema_version": "0.1.0",
      "dtype": "uint16 (RGB16, 3 channels interleaved)",
      "note": "rawler_cfa is the decoder-cutover twin (also uint16)."
    },
    {
      "id": "typed_f32",
      "shape": "circle",
      "label": "f32 typed array",
      "schema_entry": "wasm_typed_array",
      "schema_version": "0.1.0",
      "dtype": "Float64/Float32/Uint16 typed arrays across the JS<->wasm (Rust) boundary",
      "note": "JS-side view of the wasm crossing (see wasm_heap for the wasm side)."
    },
    {
      "id": "arrow",
      "shape": "bars",
      "label": "Arrow table",
      "schema_entry": "arrow_seam",
      "schema_version": "0.1.0",
      "dtype": "Apache Arrow IPC columnar (per-column validity + data buffers)",
      "note": ""
    },
    {
      "id": "json",
      "shape": "braces",
      "label": "JSON / object",
      "schema_entry": "atlas_rows",
      "schema_version": "0.1.0",
      "dtype": "hybrid per-row record (Gaia row | HYG row)",
      "note": "Keyed to the hybrid per-row record boundary (the structured-object analog)."
    },
    {
      "id": "ipc_bytes",
      "shape": "diamond",
      "label": "raw IPC bytes",
      "schema_entry": "starplates_blobs",
      "schema_version": "0.1.0",
      "dtype": "UNVERIFIED — check tools/starplates/build_release.mjs (release builder)",
      "note": ""
    },
    {
      "id": "wasm_heap",
      "shape": "chevron",
      "label": "wasm heap view",
      "schema_entry": "wasm_typed_array",
      "schema_version": "0.1.0",
      "dtype": "Float64/Float32/Uint16 typed arrays across the JS<->wasm (Rust) boundary",
      "note": "wasm-side of the same boundary as typed_f32 (linear-memory view)."
    },
    {
      "id": "wgsl",
      "shape": "hexagon",
      "label": "WGSL buffer",
      "schema_entry": "wgsl_structs",
      "schema_version": "0.1.0",
      "dtype": "WGSL struct fields (f32/u32/vecN) on the WebGPU compute path",
      "note": ""
    },
    {
      "id": "fits",
      "shape": "crossbox",
      "label": "FITS I/O",
      "schema_entry": "fits_io",
      "schema_version": "0.1.0",
      "dtype": "FITS BITPIX-typed image data (8/16/32/-32/-64) + 80-byte ASCII header cards",
      "note": ""
    }
  ],
  "nodes": [
    {
      "id": "decoder",
      "label": "Raw decode",
      "sub": "rawler_decoder.ts · libraw",
      "x": 26,
      "y": 40,
      "w": 156,
      "h": 54
    },
    {
      "id": "demosaic",
      "label": "Demosaic",
      "sub": "demosaic_pipeline.ts",
      "x": 26,
      "y": 176,
      "h": 54,
      "w": 156
    },
    {
      "id": "tauri",
      "label": "Native backend",
      "sub": "src-tauri · Rust",
      "x": 26,
      "y": 316,
      "w": 156,
      "h": 54
    },
    {
      "id": "arrow_mem",
      "label": "Arrow store",
      "sub": "core/ArrowMemory.ts",
      "x": 372,
      "y": 96,
      "w": 176,
      "h": 62
    },
    {
      "id": "worker_signal",
      "label": "Signal worker",
      "sub": "signal_worker.ts",
      "x": 372,
      "y": 306,
      "w": 176,
      "h": 54,
      "status": "dead",
      "dead_date": "2026-07-11",
      "dead_reason": "signal_worker.ts DELETED 2026-07-11 (branch cleanup/dead-workers, ROADMAP item 6): orphaned worker, never spawned (no new Worker/?worker in src). Live signal path is in-process WASM shared-heap — extract_blobs_shared @signal_processor.ts:901."
    },
    {
      "id": "wasm",
      "label": "WASM compute",
      "sub": "signal_processor · source_extractor",
      "x": 738,
      "y": 96,
      "w": 184,
      "h": 62
    },
    {
      "id": "worker_phot",
      "label": "Photometry worker",
      "sub": "photometry_worker.ts",
      "x": 738,
      "y": 292,
      "w": 184,
      "h": 54,
      "status": "dead",
      "dead_date": "2026-07-11",
      "dead_reason": "photometry_worker.ts DELETED 2026-07-11 (branch cleanup/dead-workers, ROADMAP item 6): orphaned worker, never spawned. Live photometry path is the in-process pool — refine_stars_bulk @photometry_worker_pool.ts:57 (a different file, NOT this worker)."
    }
  ],
  "edges": [
    {
      "id": "e1_raw_to_arrow",
      "from": "decoder",
      "to": "arrow_mem",
      "line_class": "shared_view",
      "start_glyph": "typed_u16",
      "end_glyph": "arrow",
      "measured": true,
      "curve": 0,
      "site": "ArrowMemory.ts:26 createRawBuffer · caller rawler_decoder.ts:364",
      "wall": "wall1_arrow_ingest_copy",
      "measurement": "raw Uint16 36MB → makeTable: readback is the SAME ArrayBuffer (ZERO-COPY)."
    },
    {
      "id": "e2_rgb_to_arrow",
      "from": "demosaic",
      "to": "arrow_mem",
      "line_class": "shared_view",
      "start_glyph": "typed_f32",
      "end_glyph": "arrow",
      "measured": true,
      "curve": 0,
      "site": "ArrowMemory.ts:37 createRgbBuffer · caller demosaic_pipeline.ts:97/113/124",
      "wall": "wall1_arrow_ingest_copy",
      "measurement": "Float32 18MP/216MB → makeTable: same ArrayBuffer + same byteOffset (ZERO-COPY); overhead = 6.44MB validity bitmap (N/8), NOT a 216MB duplicate."
    },
    {
      "id": "e3_copy_in",
      "from": "arrow_mem",
      "to": "wasm",
      "line_class": "copy",
      "start_glyph": "typed_f32",
      "end_glyph": "wasm_heap",
      "measured": true,
      "curve": -34,
      "cost_ms": 12.8121,
      "cost_payload_mb": 216,
      "gbps": 16.86,
      "site": "signal_processor.ts:897-901 · source_extractor.ts:78-88 · demosaic_engine.ts:238",
      "wall": "wall2_wasm_crossings",
      "measurement": "copy-IN heapView.set(src): O(N) memcpy, 12.81ms @216MB (16.86 GB/s, N=5 median). NB: signal_processor.ts:894 calls this an \"O(1) handoff\" — it is O(N)."
    },
    {
      "id": "e4_copy_out",
      "from": "wasm",
      "to": "arrow_mem",
      "line_class": "copy",
      "start_glyph": "wasm_heap",
      "end_glyph": "typed_f32",
      "measured": true,
      "curve": -34,
      "cost_ms": 41.0329,
      "cost_payload_mb": 216,
      "gbps": 5.26,
      "site": "signal_processor.ts / wasm-bindgen Vec return",
      "wall": "wall2_wasm_crossings",
      "measurement": "copy-OUT .slice()/Vec: O(N) memcpy, 41.03ms @216MB (5.26 GB/s). An O(1) view (new F32(memory,ptr,n)) exists but live code copies it out."
    },
    {
      "id": "e5_transfer",
      "from": "wasm",
      "to": "worker_phot",
      "line_class": "ownership_transfer",
      "start_glyph": "typed_f32",
      "end_glyph": "typed_f32",
      "measured": true,
      "curve": 0,
      "status": "dead",
      "dead_date": "2026-07-11",
      "dead_reason": "DEAD PATH — photometry_worker.ts deleted 2026-07-11 (orphaned, never spawned). The transferable round-trip below was a real micro-benchmark of the postMessage primitive, but this worker site no longer exists; live photometry runs in-process (photometry_worker_pool.ts).",
      "cost_ms": 0.1976,
      "cost_payload_mb": 200,
      "gbps": null,
      "site": "photometry_worker.ts:38 postMessage(msg, [refinedParams.buffer]) — FILE DELETED",
      "wall": "wall3_worker_clone_vs_transfer",
      "measurement": "Transferable round-trip: 0.14ms @50MB / 0.20ms @200MB — 172x / 482x faster than structuredClone. The buffer is detached from the sender (ownership moves)."
    },
    {
      "id": "e6_clone",
      "from": "arrow_mem",
      "to": "worker_signal",
      "line_class": "copy",
      "start_glyph": "json",
      "end_glyph": "json",
      "measured": true,
      "curve": 0,
      "status": "dead",
      "dead_date": "2026-07-11",
      "dead_reason": "DEAD PATH — signal_worker.ts deleted 2026-07-11 (orphaned, never spawned). The structuredClone round-trip below was a real micro-benchmark, but this worker site no longer exists; live signal extraction runs in-process (signal_processor.ts:901).",
      "cost_ms": 95.1667,
      "cost_payload_mb": 200,
      "gbps": 2,
      "site": "signal_worker.ts:23 postMessage({blobs}) — FILE DELETED",
      "wall": "wall3_worker_clone_vs_transfer",
      "measurement": "structuredClone round-trip: 24.17ms @50MB / 95.17ms @200MB (~2 GB/s). The full payload is serialized+copied — the transfer path (e5) avoids this."
    },
    {
      "id": "e7_tauri_demosaic",
      "from": "tauri",
      "to": "demosaic",
      "line_class": "copy",
      "start_glyph": "typed_u16",
      "end_glyph": "json",
      "measured": false,
      "curve": 0,
      "site": "src-tauri lib.rs:285 demosaic_native · NativeGpuBridge.ts:42",
      "wall": "wall4_tauri_ipc_static",
      "measurement": "STATIC inventory: bayerData crosses as JSON number[] (~96MB JSON string @24MP). Runtime NOT MEASURED (needs the packaged app)."
    },
    {
      "id": "e8_tauri_catalog",
      "from": "tauri",
      "to": "arrow_mem",
      "line_class": "copy",
      "start_glyph": "ipc_bytes",
      "end_glyph": "arrow",
      "measured": false,
      "curve": 26,
      "site": "src-tauri lib.rs:188-205 query_catalog_v2",
      "wall": "wall4_tauri_ipc_static",
      "measurement": "STATIC inventory: returns a raw Arrow-IPC ArrayBuffer (NO JSON) — an efficient raw-bytes path. Runtime NOT MEASURED."
    }
  ]
};
