'use strict';
/* ═══════════════════════════════════════════════════════════════════════════
   #tokens tab — TOKEN COMPOSITION panel (input · output · cache-read · cache-
   creation). Classic (non-module) script loaded BEFORE app.js; renderTokens()
   (in app.js) calls renderTokenSplitPanel() to inject this section.

   Data: window.__TOKEN_SPLIT__ (generated by gen_token_split.mjs from
   test_results/agent_runs.jsonl). A selector switches the view between the whole
   FLEET, a single SESSION (subagent aggregate), and an individual agent RUN.

   HONESTY (LAW 3): a run/session whose split could not be derived shows NOT
   MEASURED, never a guessed 0. The session view is explicit that it aggregates
   SUBAGENT runs only (orchestrator main-thread tokens are not in this log); the
   OTel note surfaces whether a complete session split exists and is fresh.
   ═══════════════════════════════════════════════════════════════════════════ */

const TKS_SEG = [
  { k: 'input',          label: 'input (fresh)',   c: 'input' },
  { k: 'output',         label: 'output',          c: 'output' },
  { k: 'cache_read',     label: 'cache read',      c: 'cread' },
  { k: 'cache_creation', label: 'cache creation',  c: 'ccreate' },
];

let _tksState = { scope: 'fleet', sessionId: null, runIdx: 0 };
let _tksWired = false;

function tksFmt(n) {
  if (n == null || Number.isNaN(n)) return 'NOT MEASURED';
  if (n >= 1e9) return (n / 1e9).toFixed(2) + 'B';
  if (n >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (n >= 1e3) return (n / 1e3).toFixed(1) + 'k';
  return String(n);
}
function tksEsc(s) { return typeof esc === 'function' ? esc(String(s)) : String(s); }
function tksTs(s) { return (typeof fmtTs === 'function') ? fmtTs(s) : (s ? tksEsc(String(s).slice(0, 16).replace('T', ' ')) : 'NOT RECORDED'); }

function tksTotal(split) { return TKS_SEG.reduce((a, s) => a + (Number(split[s.k]) || 0), 0); }

function tksBar(split) {
  const total = tksTotal(split) || 1;
  const segs = TKS_SEG.map((s) => {
    const v = Number(split[s.k]) || 0;
    const pct = 100 * v / total;
    return `<span class="tks-seg tks-${s.c}" style="width:${pct.toFixed(3)}%"
      title="${tksEsc(s.label)}: ${tksEsc(tksFmt(v))} (${pct.toFixed(1)}%)"></span>`;
  }).join('');
  return `<div class="tks-bar" role="img" aria-label="token composition stacked bar">${segs}</div>`;
}

function tksTable(split) {
  const total = tksTotal(split) || 1;
  return `<div class="tks-rows">` + TKS_SEG.map((s) => {
    const v = Number(split[s.k]) || 0;
    const pct = 100 * v / total;
    return `<div class="tks-row">
      <span class="tks-sw tks-${s.c}"></span>
      <span class="tks-k">${tksEsc(s.label)}</span>
      <span class="tks-v">${tksEsc(tksFmt(v))}</span>
      <span class="tks-p">${pct.toFixed(1)}%</span>
    </div>`;
  }).join('') + `</div>`;
}

function tksComposition(split, metaHtml) {
  const cacheShare = (() => {
    const total = tksTotal(split) || 1;
    return 100 * ((Number(split.cache_read) || 0) + (Number(split.cache_creation) || 0)) / total;
  })();
  return `<div class="tks-comp">
    ${tksBar(split)}
    <div class="tks-comp-body">
      ${tksTable(split)}
      <div class="tks-meta">${metaHtml}
        <div class="tks-headline">cache (read + creation) = <b>${cacheShare.toFixed(1)}%</b> of this view's tokens</div>
      </div>
    </div>
  </div>`;
}

function tksScopeBtns() {
  const opts = [['fleet', 'Fleet'], ['session', 'Per session'], ['run', 'Per agent run']];
  return `<div class="tks-scope">` + opts.map(([id, lbl]) =>
    `<button type="button" class="tks-scope-btn${_tksState.scope === id ? ' on' : ''}" data-scope="${id}">${lbl}</button>`
  ).join('') + `</div>`;
}

function renderTokenSplitPanel() {
  const d = (typeof window !== 'undefined') && window.__TOKEN_SPLIT__;
  tksWire();
  if (!d || !d.available) {
    return `<div id="tks-panel"><div class="none-logged" style="padding:16px 4px">
      <b>NOT MEASURED.</b> The token-composition feed (<code>token_split.js</code>) is absent or empty.
      Generate it with <code>node tools/theses/dashboard/ui/gen_token_split.mjs</code>
      (derives the split from <code>test_results/agent_runs.jsonl</code>).</div></div>`;
  }

  const f = d.fleet || {};
  const otel = d.otel || {};
  let selector = tksScopeBtns();
  let view = '';

  if (_tksState.scope === 'fleet') {
    const meta = `<div class="tks-metaline">${f.measured_runs != null ? tksEsc(f.measured_runs) : '?'} measured runs
      · <span class="tks-nm">${f.unmeasured_runs != null ? tksEsc(f.unmeasured_runs) : '?'} unmeasured (NOT MEASURED)</span>
      · ${f.sessions != null ? tksEsc(f.sessions) : '?'} sessions
      · total ${tksEsc(tksFmt(f.total))} tokens</div>`;
    view = tksComposition(f.split || {}, meta);
  } else if (_tksState.scope === 'session') {
    const list = Array.isArray(d.sessions) ? d.sessions : [];
    if (!list.length) { view = `<div class="none-logged">NO SESSIONS MEASURED</div>`; }
    else {
      if (!_tksState.sessionId || !list.some((s) => s.id === _tksState.sessionId)) _tksState.sessionId = list[0].id;
      const s = list.find((x) => x.id === _tksState.sessionId) || list[0];
      selector += `<select class="tks-select" data-kind="session" aria-label="pick a session">` +
        list.map((x) => `<option value="${tksEsc(x.id)}"${x.id === s.id ? ' selected' : ''}>${tksEsc(x.short)} · ${tksEsc(x.runs)} runs · ${tksEsc(tksFmt(x.total))} · ${tksTs(x.last_ts)}</option>`).join('') +
        `</select>`;
      const meta = `<div class="tks-metaline">session <code>${tksEsc(s.short)}</code>
        · ${tksEsc(s.runs)} subagent runs · ${s.models && s.models.length ? tksEsc(s.models.join(' ')) : 'model NOT RECORDED'}
        <br>${tksTs(s.first_ts)} → ${tksTs(s.last_ts)}</div>
        <div class="tks-caveat">SUBAGENT runs only — the orchestrator main-thread tokens for this session are not in agent_runs.jsonl.
        ${otel.stale ? 'OTel (which would include them) is STALE for this window.' : (otel.present ? '' : 'OTel not available.')}</div>`;
      view = tksComposition(s.split || {}, meta);
    }
  } else { // run
    const runs = Array.isArray(d.runs) ? d.runs : [];
    if (!runs.length) { view = `<div class="none-logged">NO RUNS MEASURED</div>`; }
    else {
      if (_tksState.runIdx == null || _tksState.runIdx < 0 || _tksState.runIdx >= runs.length) _tksState.runIdx = 0;
      const r = runs[_tksState.runIdx];
      selector += `<select class="tks-select" data-kind="run" aria-label="pick an agent run">` +
        runs.map((x, i) => `<option value="${i}"${i === _tksState.runIdx ? ' selected' : ''}>${tksTs(x.ts)} · ${tksEsc(x.agent)} · ${tksEsc(x.model || 'model NOT RECORDED')}</option>`).join('') +
        `</select>`;
      const meta = `<div class="tks-metaline"><b>${tksEsc(r.agent)}</b> · ${tksEsc(r.model || 'model NOT RECORDED')}
        · session <code>${tksEsc(r.session || '?')}</code> · ${tksTs(r.ts)} · total ${tksEsc(tksFmt(tksTotal(r.split)))} tokens</div>`;
      view = tksComposition(r.split || {}, meta);
    }
  }

  const otelLine = `<div class="tks-otel">${otel.present
    ? `OTel session metrics: ${otel.stale ? '<span class="tks-nm">STALE</span>' : 'current'} · last write ${tksEsc((otel.last_write || '').slice(0, 10))}${otel.size_mb ? ' · ' + tksEsc(otel.size_mb) + 'MB' : ''}. ${tksEsc(otel.note || '')}`
    : tksEsc(otel.note || 'OTel session metrics NOT AVAILABLE.')}</div>`;

  return `<div id="tks-panel">
    ${selector}
    ${view}
    ${otelLine}
  </div>`;
}

function tksRepaint() {
  const el = (typeof document !== 'undefined') && document.getElementById('tks-panel');
  if (el) el.outerHTML = renderTokenSplitPanel();
}

function tksWire() {
  if (_tksWired || typeof document === 'undefined') return;
  _tksWired = true;
  document.addEventListener('click', (e) => {
    const b = e.target.closest && e.target.closest('.tks-scope-btn');
    if (!b) return;
    _tksState.scope = b.dataset.scope;
    tksRepaint();
  });
  document.addEventListener('change', (e) => {
    const sel = e.target.closest && e.target.closest('.tks-select');
    if (!sel) return;
    if (sel.dataset.kind === 'session') _tksState.sessionId = sel.value;
    else if (sel.dataset.kind === 'run') _tksState.runIdx = parseInt(sel.value, 10);
    tksRepaint();
  });
}
