'use strict';
/* ═══════════════════════════════════════════════════════════════════════════
   #flow tab — PROCESSING-STAGE CHAIN (primary content).

   Classic (non-module) script, loaded BEFORE app.js and AFTER tab_flow_edges.js
   so it may reuse the geometry helpers defined there (flowCenter, flowBorderPoint,
   flowQuad) and app.js's esc(). Renders the shared post-C1 stage chain from the
   global window.__FLOW_STAGES__ (generated by gen_flow_stages.mjs).

   HONESTY (LAW 3): every node/edge carries a file:line CITATION (surfaced in the
   hover tooltip) into the SOURCE_REF branch it reflects. The view is bandered
   with that branch+sha so it is honest about describing PRE-MERGE truth. A node
   whose live-path status is not confirmed renders a NOT VERIFIED tag. Absent data
   file → NOT AVAILABLE, nothing invented.

   renderFlow() (bottom) is what the #flow tab actually calls: the stage chain
   FIRST, then the existing memory/transfer edge-semantics map (renderFlowEdges)
   as a clearly-labelled secondary "memory boundaries (LAW 7)" section — the two
   honest lenses on the same pipeline, neither destroyed.
   ═══════════════════════════════════════════════════════════════════════════ */

/* class → colour token (tab-local, see tab_flow_stages.css) */
const STAGE_COLOR = {
  always: 'var(--stage-always)',
  conditional: 'var(--stage-conditional)',
  render: 'var(--stage-render)',
  product: 'var(--stage-product)',
};

function stageEsc(s) { return typeof esc === 'function' ? esc(String(s)) : String(s); }

function stageDashFor(cls) {
  if (cls === 'conditional') return '7 5';
  if (cls === 'render') return '1.5 5';
  if (cls === 'fold') return '4 4';
  return ''; // flow = solid
}
function stageEdgeColor(cls) {
  if (cls === 'conditional') return 'var(--stage-conditional)';
  if (cls === 'render') return 'var(--stage-render)';
  if (cls === 'fold') return 'var(--stage-fold)';
  return 'var(--stage-flow)';
}
function stageEdgeWidth(cls) { return cls === 'fold' ? 1.4 : cls === 'render' ? 1.8 : 2.2; }

/* ── main render ─────────────────────────────────────────────────────────── */
function renderFlowStages() {
  const model = (typeof window !== 'undefined') && window.__FLOW_STAGES__;
  if (!model || !Array.isArray(model.nodes) || !Array.isArray(model.edges)) {
    return `<div class="subhead"><span class="src fixture">DATA FILE NOT LOADED</span><span class="spacer"></span></div>
      <div class="offline"><div class="o-badge">NOT AVAILABLE</div>
        <p>The stage-chain data file (<code>flow_stages.js</code>) did not load, so this
           tab has no cited stage graph to draw. Nothing is fabricated in its place.
           Regenerate with <code>node tools/theses/dashboard/ui/gen_flow_stages.mjs</code>.</p></div>`;
  }

  const nodeById = {};
  model.nodes.forEach((n) => { nodeById[n.id] = n; });
  const vb = model.viewbox || { w: 960, h: 1020 };
  const src = model.source_ref || {};
  const verifiedCount = model.edges.filter((e) => e.verified).length;

  /* ── step-lane bands (faint) ── */
  const bandByStep = {};
  model.nodes.forEach((n) => {
    const b = bandByStep[n.step] || { min: Infinity, max: -Infinity };
    b.min = Math.min(b.min, n.y); b.max = Math.max(b.max, n.y + n.h);
    bandByStep[n.step] = b;
  });
  let bandSvg = '';
  (model.steps || []).forEach((s, i) => {
    const b = bandByStep[s.id];
    if (!b) return;
    const y = b.min - 10, h = (b.max - b.min) + 20;
    bandSvg += `<g class="stage-band ${i % 2 ? 'odd' : 'even'}">
      <rect x="2" y="${y.toFixed(1)}" width="${vb.w - 4}" height="${h.toFixed(1)}" rx="6"/>
      <text x="12" y="${(y + 16).toFixed(1)}" class="stage-band-t">${stageEsc(s.label)}</text>
      <title>${stageEsc(s.label + ' — ' + (s.cite || ''))}</title>
    </g>`;
  });

  /* ── edges (under nodes) ── */
  let edgeSvg = '';
  model.edges.forEach((e) => {
    const A = nodeById[e.from], B = nodeById[e.to];
    if (!A || !B) return;
    const ac = flowCenter(A), bc = flowCenter(B);
    const p0 = flowBorderPoint(A, bc.x, bc.y, 3);
    const p1 = flowBorderPoint(B, ac.x, ac.y, 3);
    const dx = p1.x - p0.x, dy = p1.y - p0.y;
    const len = Math.hypot(dx, dy) || 1;
    // horizontal-ish edges bow slightly so parallel fold-lines separate
    const off = Math.abs(dx) > Math.abs(dy) ? (dy >= 0 ? 16 : -16) : 0;
    const mid = { x: (p0.x + p1.x) / 2, y: (p0.y + p1.y) / 2 };
    const cp = { x: mid.x + (-dy / len) * off, y: mid.y + (dx / len) * off };

    const color = stageEdgeColor(e.class);
    const width = stageEdgeWidth(e.class);
    const dash = stageDashFor(e.class);
    const dashAttr = dash ? `stroke-dasharray:${dash};` : '';

    const headAt = flowQuad(p0, cp, p1, 0.965);
    const preHead = flowQuad(p0, cp, p1, 0.9);
    const ha = Math.atan2(headAt.y - preHead.y, headAt.x - preHead.x);
    const hl = 7.5;
    const hx1 = headAt.x - hl * Math.cos(ha - 0.42), hy1 = headAt.y - hl * Math.sin(ha - 0.42);
    const hx2 = headAt.x - hl * Math.cos(ha + 0.42), hy2 = headAt.y - hl * Math.sin(ha + 0.42);
    const lbl = flowQuad(p0, cp, p1, 0.5);

    const tip = [
      `${e.from} → ${e.to}`,
      e.product ? `product: ${e.product}` : '',
      `class: ${e.class}`,
      e.cite ? `cite: ${e.cite}` : '',
      e.verified ? 'VERIFIED (cited call site)' : 'NOT VERIFIED',
    ].filter(Boolean).join('\n');

    edgeSvg += `<g class="stage-edge cls-${e.class}${e.verified ? '' : ' unverified'}">
      <title>${stageEsc(tip)}</title>
      <path d="M ${p0.x.toFixed(1)} ${p0.y.toFixed(1)} Q ${cp.x.toFixed(1)} ${cp.y.toFixed(1)} ${p1.x.toFixed(1)} ${p1.y.toFixed(1)}"
        style="fill:none;stroke:${color};stroke-width:${width};${dashAttr}stroke-linecap:round"/>
      <polygon points="${headAt.x.toFixed(1)},${headAt.y.toFixed(1)} ${hx1.toFixed(1)},${hy1.toFixed(1)} ${hx2.toFixed(1)},${hy2.toFixed(1)}"
        style="fill:${color}"/>
      ${e.product ? `<text x="${lbl.x.toFixed(1)}" y="${(lbl.y - 3).toFixed(1)}" text-anchor="middle" class="stage-edge-lbl">${stageEsc(e.product)}</text>` : ''}
    </g>`;
  });

  /* ── nodes (over edges) ── */
  let nodeSvg = '';
  model.nodes.forEach((n) => {
    const color = STAGE_COLOR[n.class] || STAGE_COLOR.always;
    const stepN = (model.steps || []).find((s) => s.id === n.step);
    const badge = stepN ? 'S' + stepN.n : '';
    const tip = [
      `${n.label}`,
      n.role ? n.role : '',
      n.file ? `impl: ${n.file}` : '',
      n.cite ? `cite: ${n.cite}` : '',
      `class: ${n.class}`,
      n.verified ? 'VERIFIED (cited)' : 'NOT VERIFIED',
    ].filter(Boolean).join('\n');
    nodeSvg += `<g class="stage-node cls-${n.class}${n.verified ? '' : ' unverified'}">
      <title>${stageEsc(tip)}</title>
      <rect x="${n.x}" y="${n.y}" width="${n.w}" height="${n.h}" rx="8"/>
      <rect x="${n.x}" y="${n.y}" width="5" height="${n.h}" rx="2.5" style="fill:${color}"/>
      <text x="${n.x + 15}" y="${n.y + 21}" class="stage-node-t">${stageEsc(n.label)}</text>
      <text x="${n.x + 15}" y="${n.y + 37}" class="stage-node-f">${stageEsc(n.file || '')}</text>
      ${badge ? `<text x="${n.x + n.w - 8}" y="${n.y + 17}" text-anchor="end" class="stage-node-badge">${stageEsc(badge)}</text>` : ''}
      ${n.verified ? '' : `<text x="${n.x + n.w - 8}" y="${n.y + n.h - 7}" text-anchor="end" class="stage-node-nv">NOT VERIFIED</text>`}
    </g>`;
  });

  const svg = `<div class="stage-canvas">
    <svg viewBox="0 0 ${vb.w} ${vb.h}" preserveAspectRatio="xMidYMid meet" role="img"
      aria-label="Post-C1 processing stage chain">
      ${bandSvg}${edgeSvg}${nodeSvg}
    </svg></div>`;

  const banner = `<div class="stage-srcbanner">
    <span class="stage-src-tag">SOURCE</span>
    <span class="stage-src-ref"><b>${stageEsc(src.branch || '?')}</b> @ <code>${stageEsc(src.sha || '?')}</code></span>
    <span class="stage-src-note">${stageEsc(src.role || '')}</span>
    <span class="stage-src-meta">receipt schema ${stageEsc(src.receipt_schema_version || '?')} · ${model.nodes.length} stages · ${verifiedCount}/${model.edges.length} edges verified · generated ${stageEsc((model.generated_at || '').slice(0, 16).replace('T', ' '))}</span>
  </div>`;

  const subhead = `<div class="subhead">
    <span class="src static">STATIC · cited stage graph</span>
    <span class="flow-sub-meta">${stageEsc(src.verified_by || '')}</span>
    <span class="spacer"></span>
  </div>`;

  return subhead + banner + svg + stageLegend(model);
}

/* ── legend ──────────────────────────────────────────────────────────────── */
function stageLegend(model) {
  const nodeRows = (model.node_classes || []).map((c) => `
    <div class="stage-leg-row">
      <span class="stage-leg-chip cls-${c.id}"></span>
      <div class="stage-leg-text"><b>${stageEsc(c.label)}</b><span>${stageEsc(c.meaning)}</span></div>
    </div>`).join('');

  const edgeRows = (model.edge_classes || []).map((c) => {
    const color = stageEdgeColor(c.id);
    const dash = stageDashFor(c.id);
    const dashAttr = dash ? `stroke-dasharray:${dash};` : '';
    return `<div class="stage-leg-row">
      <svg viewBox="0 0 60 14" class="stage-leg-line" aria-hidden="true">
        <line x1="4" y1="7" x2="56" y2="7" style="stroke:${color};stroke-width:${stageEdgeWidth(c.id)};${dashAttr}stroke-linecap:round"/>
      </svg>
      <div class="stage-leg-text"><b style="color:${color}">${stageEsc(c.label)}</b><span>${stageEsc(c.meaning)}</span></div>
    </div>`;
  }).join('');

  const steps = (model.steps || []).map((s) =>
    `<span class="stage-step-pill"><b>S${s.n}</b> ${stageEsc(s.label.replace(/^STEP \d+ · /, ''))} <code>${stageEsc(s.cite)}</code></span>`).join('');

  return `<div class="stage-legend">
    <h2 class="rule">wizard steps — the 6 top-level <code>withStage</code> phases (orchestrator_session + headless driver share this spine)</h2>
    <div class="stage-steps">${steps}</div>

    <h2 class="rule">stage classes</h2>
    <div class="stage-leg-grid">${nodeRows}</div>

    <h2 class="rule">edge classes — data-product dependencies</h2>
    <div class="stage-leg-grid">${edgeRows}</div>

    <h2 class="rule">honesty</h2>
    <div class="flow-honesty">
      <p>Every stage node and every edge carries a <b>file:line citation</b> (hover any node or line) into
        <b>${stageEsc((model.source_ref || {}).branch || '')} @ ${stageEsc((model.source_ref || {}).sha || '')}</b> —
        the imminent-future main, ahead of the branch this dashboard is committed on. This view is honest that it
        describes <b>pre-merge</b> truth.</p>
      <p><span class="flow-hon-chip notmeasured">NOT VERIFIED</span> a node/edge whose live-path status could not be
        confirmed is tagged as such and never asserted. <code>conditional</code> stages are guarded / default-off and
        render honest-absent when they do not run; <code>render</code> stages are display-only (byte-identical off, LAW 1).</p>
    </div>
  </div>`;
}

/* ── combined #flow renderer: stage chain FIRST, memory map SECOND ───────── */
function renderFlow() {
  const stages = renderFlowStages();
  const memory = (typeof renderFlowEdges === 'function')
    ? `<div class="stage-section-divider">
         <h2 class="rule">memory boundaries — data-transfer semantics (LAW 7) <span class="rule-sub">a second, orthogonal lens: how bytes move between memory domains, not stage order</span></h2>
       </div>${renderFlowEdges()}`
    : '';
  return stages + memory;
}
