// tools/atlas/verify_atlas_repro.mjs
// ═══════════════════════════════════════════════════════════════════════════
// ATLAS BYTE-PROOF — the standing "we can regenerate the frozen atlas" gate
// ═══════════════════════════════════════════════════════════════════════════
//
// Proves that the shipped, gitignored, IRREPLACEABLE deep catalog
// (public/atlas/level_1_anchors.json, level_2_pattern.json, and the 36
// sectors/level_3_sector_0..35.json) is byte-for-byte REGENERABLE from the
// committed inputs + tooling:
//
//   gaia_vanguard_dr3.csv  --[generate_star_atlas.ts]-->  Gaia sector shards
//                          --[rebucket_sectors.mjs]------>  Gaia-only sectors
//   + named HYG cells      --[merge_hyg_sectors.mjs]----->  final sectors
//   gaia bright stars      --[saveLayer]----------------->  L1/L2 anchors
//
// WHY A SELF-CONTAINED REFERENCE REPRODUCER (LAW 4 note): the generator is a .ts
// file and there is NO tsx/loader on the tools lanes, so it cannot be imported
// here. This harness therefore carries an INDEPENDENT reference re-implementation
// of the generator + rebucket steps (cited to their exact source lines) -- which
// is the RIGHT shape for a byte-proof: an independent path that lands on the same
// bytes is a stronger claim than re-running the identical script. The HYG-merge
// RULE is NOT duplicated -- it is imported from merge_hyg_sectors.mjs (the tool
// under proof).
//
// ─── LOAD-BEARING FINDING (contradicts LAYOUT_TRANSCRIPTION section 2 NOTE) ───
// The audit asserted "generator bucketing is IRRELEVANT to repro." MEASURED here:
// that is TRUE for row MEMBERSHIP but FALSE for BYTE ORDER. The rebucketer collects
// rows in first-seen order across readdirSync(files) x within-file(CSV) order, so
// the generator's (buggy) line-90 bucketing -- which decides WHICH shard each row
// lands in -- permutes the final within-sector order. The frozen atlas was built
// with the pre-fix BUGGY bucketing (ra-DEGREES treated as hours), so this harness
// MUST replicate that legacy bucketing to hit the frozen bytes. A full regen with
// the CORRECTED generator (default now) is CONTENT-identical but BYTE-different and
// would require an owner rebaseline of the frozen artifact (out of scope for step 1).
//
// Serialization facts (MEASURED against the shipped files):
//   - minified sectors: LF line endings, '[' + rows.join(',\n') + ']'.
//   - L1/L2 anchors: JSON.stringify(data,null,2) but with CRLF line endings (a
//     Windows-write artifact of the shipped pretty files; content is identical to
//     the LF JSON.stringify output). This harness applies LF->CRLF to match.
//
// Usage:
//   node --max-old-space-size=8192 tools/atlas/verify_atlas_repro.mjs \
//     [--vanguard <csv>] [--atlas <public/atlas dir>] \
//     [--manifest <out manifest json>] [--out <dir to also WRITE regen>] [--write-manifest]
// Exit code 0 iff all 38 files are byte-EQUAL (or the honest content-hash fallback
// passes with its reason recorded). Nonzero on any CONTENT difference.

import fs from 'node:fs';
import path from 'node:path';
import readline from 'node:readline';
import { createHash } from 'node:crypto';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { hygRowsForSector, serializeSector, SECTOR_COUNT, HYG_MAG_THRESHOLD } from './merge_hyg_sectors.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const argv = process.argv.slice(2);
const val = (flag, def) => { const i = argv.indexOf(flag); return i >= 0 ? argv[i + 1] : def; };
const has = (flag) => argv.includes(flag);

const VANGUARD = val('--vanguard', path.join(repoRoot, 'gaia_vanguard_dr3.csv'));
const ATLAS = val('--atlas', path.join(repoRoot, 'public', 'atlas'));
const NAMED_DIR = path.join(ATLAS, 'sectors');
const MANIFEST_OUT = val('--manifest', path.join(repoRoot, 'tools', 'atlas', 'atlas_repro_manifest.json'));
const OUT_DIR = val('--out', null); // if set, ALSO write regenerated bytes here
const WRITE_MANIFEST = has('--write-manifest');

const MAG_LIMIT_MEM = 10.0; // generate_star_atlas.ts:42 -- mag<10 -> L1/L2, else L3.

// ─── generate_star_atlas.ts row logic (exact replica, cited lines) ───────────
// minifiedStar (generate_star_atlas.ts:135-147)
function minifiedStar(s) {
    return {
        id: s.id,
        proper: s.proper || undefined,
        ra: Math.round(s.ra * 10000) / 10000,
        dec: Math.round(s.dec * 10000) / 10000,
        mag_g: Math.round(s.mag_g * 1000) / 1000,
        bp_rp: Math.round(s.bp_rp * 1000) / 1000,
        pm_ra: Math.round(s.pm_ra * 10) / 10,
        pm_dec: Math.round(s.pm_dec * 10) / 10,
        source_id: s.source_id,
    };
}
// LEGACY buggy bucketing (generate_star_atlas.ts:90 pre-fix): ra-DEGREES % 24.
// Pinned here to reproduce the FROZEN artifact (see finding above).
function legacyShard(raDeg, dec) {
    const r = ((raDeg % 24) + 24) % 24;
    const raIndex = Math.min(5, Math.floor(r / 4));
    const decIndex = Math.min(5, Math.floor((Math.max(-90, Math.min(90, dec)) + 90) / 30));
    return decIndex * 6 + raIndex;
}
// TRUE bucketing (star_catalog_adapter.getSectorId / rebucket_sectors.mjs:24-27):
// ra-DEGREES -> hours via /15.
function trueSector(raDeg, dec) {
    const raH = (((raDeg / 15) % 24) + 24) % 24;
    const raIndex = Math.min(5, Math.floor(raH / 4));
    const decIndex = Math.min(5, Math.floor((Math.max(-90, Math.min(90, dec)) + 90) / 30));
    return decIndex * 6 + raIndex;
}

async function regenerate() {
    // Pass 1: stream vanguard, split L1/L2 bright vs L3 shards (legacy bucketed).
    const shards = Array.from({ length: SECTOR_COUNT }, () => []); // shards[legacyId] = [{str,tb,sid,finite}]
    const bright = []; // full star objects, mag < 10 (for anchors)
    const rl = readline.createInterface({ input: fs.createReadStream(VANGUARD), crlfDelay: Infinity });
    let isHeader = true; const H = {};
    for await (const line of rl) {
        const cols = line.split(',').map((c) => c.trim().replace(/^"|"$/g, ''));
        if (isHeader) { cols.forEach((c, i) => { H[c] = i; }); isHeader = false; continue; }
        const sid = parseInt(cols[H['source_id']]) || 0; if (sid <= 0) continue;
        const mag = parseFloat(cols[H['phot_g_mean_mag']] ?? cols[H['mag']]); if (Number.isNaN(mag)) continue;
        const star = {
            id: parseInt(cols[H['id']]) || 0,
            proper: cols[H['proper']] || '',
            ra: parseFloat(cols[H['ra']]),
            dec: parseFloat(cols[H['dec']]),
            mag_g: mag,
            bp_rp: parseFloat(cols[H['bp_rp']]) || 0.0,
            pm_ra: parseFloat(cols[H['pmra']]) || 0.0,
            pm_dec: parseFloat(cols[H['pmdec']]) || 0.0,
            source_id: sid,
        };
        if (mag < MAG_LIMIT_MEM) { bright.push(star); continue; }
        const legacyId = legacyShard(star.ra, star.dec);
        if (!Number.isInteger(legacyId) || legacyId < 0 || legacyId >= SECTOR_COUNT) continue; // non-\d+ shard -> rebucket never reads it
        const m = minifiedStar(star);
        const finite = Number.isFinite(m.ra) && Number.isFinite(m.dec) && Number.isFinite(m.mag_g);
        shards[legacyId].push({ str: JSON.stringify(m), tb: finite ? trueSector(m.ra, m.dec) : -1, sid: m.source_id, finite });
    }

    // Pass 2: emulate rebucket_sectors.mjs -- iterate shard files in readdirSync
    // (lexicographic on Windows NTFS; empirically byte-confirmed) order, dedup by
    // source_id, drop non-finite -> Gaia-only sectors in first-seen order.
    const shardOrder = Array.from({ length: SECTOR_COUNT }, (_, i) => i)
        .sort((a, b) => (`level_3_sector_${a}.json` < `level_3_sector_${b}.json` ? -1 : 1));
    const gaia = Array.from({ length: SECTOR_COUNT }, () => []);
    const seen = Array.from({ length: SECTOR_COUNT }, () => new Set());
    for (const shardId of shardOrder) {
        for (const row of shards[shardId]) {
            if (!row.finite) continue;
            const key = row.sid ?? row.str;
            if (seen[row.tb].has(key)) continue;
            seen[row.tb].add(key);
            gaia[row.tb].push(row.str);
        }
    }

    // Pass 3: HYG merge (imported rule) + serialize each final sector.
    const sectorTexts = [];
    for (let id = 0; id < SECTOR_COUNT; id++) {
        const hyg = hygRowsForSector(NAMED_DIR, id, HYG_MAG_THRESHOLD);
        sectorTexts.push(serializeSector(gaia[id], hyg));
    }

    // Anchors: saveLayer (generate_star_atlas.ts:110-121,149-152). Sort raw mag_g
    // (stable), slice top 5000 / next 5000, pretty-print, apply shipped CRLF.
    bright.sort((a, b) => a.mag_g - b.mag_g);
    const l1 = JSON.stringify(bright.slice(0, 5000).map(minifiedStar), null, 2).replace(/\n/g, '\r\n');
    const l2 = JSON.stringify(bright.slice(5000, 10000).map(minifiedStar), null, 2).replace(/\n/g, '\r\n');

    return { sectorTexts, l1, l2 };
}

const sha256 = (buf) => createHash('sha256').update(buf).digest('hex');
const md5 = (buf) => createHash('md5').update(buf).digest('hex');

async function main() {
    const t0 = Date.now();
    console.log(`atlas byte-proof: vanguard=${VANGUARD}`);
    console.log(`                  atlas=${ATLAS}`);
    const { sectorTexts, l1, l2 } = await regenerate();

    // Files to prove: 2 anchors + 36 sectors. Each entry records the mode used.
    const targets = [
        { rel: 'level_1_anchors.json', abs: path.join(ATLAS, 'level_1_anchors.json'), text: l1, pretty: true },
        { rel: 'level_2_pattern.json', abs: path.join(ATLAS, 'level_2_pattern.json'), text: l2, pretty: true },
    ];
    for (let id = 0; id < SECTOR_COUNT; id++) {
        targets.push({ rel: `sectors/level_3_sector_${id}.json`, abs: path.join(NAMED_DIR, `level_3_sector_${id}.json`), text: sectorTexts[id], pretty: false });
    }

    const files = {}; let exact = 0, contentOnly = 0, fail = 0;
    for (const t of targets) {
        const shipBuf = fs.readFileSync(t.abs);
        const regenBuf = Buffer.from(t.text, 'utf8');
        const shipSha = sha256(shipBuf), regenSha = sha256(regenBuf);
        let verdict, reason = null;
        if (shipSha === regenSha) { verdict = 'BYTE_EXACT'; exact++; }
        else {
            // Honest fallback ONLY on formatting/order grounds. Content-hash = sha256
            // of the parsed rows re-serialized canonically (LF, order-preserved).
            const shipRows = JSON.parse(shipBuf.toString('utf8'));
            const regenRows = JSON.parse(regenBuf.toString('utf8'));
            const canon = (rows) => rows.map((r) => JSON.stringify(r)).join('\n');
            const shipContent = sha256(canon(shipRows)), regenContent = sha256(canon(regenRows));
            if (shipContent === regenContent) {
                // Same rows, same ORDER -> only whitespace/line-endings differ.
                verdict = 'CONTENT_EQUAL'; contentOnly++;
                reason = 'byte diff is whitespace/line-endings only (rows + order identical)';
            } else {
                // Order-normalized last resort, to classify the failure honestly.
                const sortCanon = (rows) => rows.map((r) => JSON.stringify(r)).sort().join('\n');
                const orderNorm = sha256(sortCanon(shipRows)) === sha256(sortCanon(regenRows));
                verdict = 'CONTENT_DIFF'; fail++;
                reason = orderNorm ? 'ROW ORDER differs (membership identical) -- STOP: investigate'
                    : `ROW MEMBERSHIP differs (ship ${shipRows.length} vs regen ${regenRows.length}) -- STOP: content mismatch`;
            }
        }
        files[t.rel] = { sha256: shipSha, bytes: shipBuf.length, regen_sha256: regenSha, verdict, ...(reason ? { reason } : {}) };
        if (OUT_DIR) { const op = path.join(OUT_DIR, t.rel); fs.mkdirSync(path.dirname(op), { recursive: true }); fs.writeFileSync(op, t.text); }
        const mark = verdict === 'BYTE_EXACT' ? 'OK ' : verdict === 'CONTENT_EQUAL' ? '~fmt' : 'FAIL';
        console.log(`  [${mark}] ${t.rel.padEnd(34)} ${verdict}${reason ? '  (' + reason + ')' : ''}`);
    }

    // Aggregate md5 over the sorted per-file SHIPPED sha256 map -- the atlas boundary
    // golden fingerprint recorded in the LAW-7 goldenVector manifest.
    const sortedShaLines = Object.keys(files).sort().map((k) => `${k}:${files[k].sha256}`).join('\n');
    const aggregate_md5 = md5(sortedShaLines);

    const manifest = {
        boundary: 'atlas_rows',
        description: 'LAW-7 golden fingerprint of the shipped deep catalog (2 anchors + 36 sectors). '
            + 'SHA-256 per file; aggregate_md5 = md5 of the sorted "path:sha256" lines. Raw bytes are '
            + 'gitignored/local-only (public/atlas, 338MB) -- this manifest is the committed pointer.',
        generated: '2026-07-11',
        reproHarness: 'tools/atlas/verify_atlas_repro.mjs',
        mergeTool: 'tools/atlas/merge_hyg_sectors.mjs',
        inputs: {
            gaia_vanguard: 'gaia_vanguard_dr3.csv (local-only; header source_id,ra,dec,phot_g_mean_mag,bp_rp,pmra,pmdec; ra DEG)',
            hyg_named_cells: 'public/atlas/sectors/sector_RA*_DEC*.json (36 named HYG cells; ra HOURS)',
        },
        serialization: {
            sectors: "minified LF: '[' + rows.join(',\\n') + ']' (Gaia block then HYG block, mag>6.8)",
            anchors: 'JSON.stringify(data,null,2) with CRLF line endings (shipped pretty-file convention)',
            legacy_bucketing: 'FROZEN artifact built with pre-line-90-fix ra%24 shard bucketing (order-load-bearing; see harness header)',
        },
        summary: { total: targets.length, byte_exact: exact, content_equal_fmt: contentOnly, content_diff: fail },
        aggregate_md5,
        files,
    };

    console.log('\n──────────────────────────────────────────────────────────────');
    console.log(`VERDICT: byte-exact ${exact}/${targets.length}  |  content-equal(fmt) ${contentOnly}  |  content-diff ${fail}`);
    console.log(`aggregate_md5 = ${aggregate_md5}`);
    console.log(`elapsed ${(Date.now() - t0) / 1000}s`);
    if (WRITE_MANIFEST) {
        fs.mkdirSync(path.dirname(MANIFEST_OUT), { recursive: true });
        fs.writeFileSync(MANIFEST_OUT, JSON.stringify(manifest, null, 2));
        console.log(`manifest written: ${MANIFEST_OUT}`);
    } else {
        console.log('(manifest NOT written; pass --write-manifest to persist)');
    }
    process.exit(fail > 0 ? 1 : 0);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    main().catch((e) => { console.error(e); process.exit(1); });
}
