/**
 * â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
 * LIGHTROOM PRESET SCHEMA â€” Adobe XMP Data Model
 * â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
 *
 * Defines the data structures for representing Lightroom/Camera Raw
 * edit parameters, and generates valid Adobe .xmp preset files
 * that can be imported directly into Lightroom Classic or ACR.
 */

// â”€â”€â”€ TYPES â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export interface ToneCurvePoint {
  /** Input value (0-255) */
  x: number;
  /** Output value (0-255) */
  y: number;
}

export interface HSLChannel {
  /** Hue shift (-180 to +180) */
  hue: number;
  /** Saturation adjustment (-100 to +100) */
  saturation: number;
  /** luminance adjustment (-100 to +100) */
  luminance: number;
}

export interface EditRecipe {
  /** Preset name */
  name: string;
  /** Description */
  description: string;

  // â”€â”€ Global Adjustments â”€â”€
  /** Exposure compensation (-5.0 to +5.0) */
  exposure: number;
  /** Contrast (-100 to +100) */
  contrast: number;
  /** Highlights recovery (-100 to +100) */
  highlights: number;
  /** Shadows fill (-100 to +100) */
  shadows: number;
  /** Whites clipping (-100 to +100) */
  whites: number;
  /** Blacks clipping (-100 to +100) */
  blacks: number;
  /** Texture (midtone detail, -100 to +100) */
  texture: number;
  /** Clarity (midtone contrast, -100 to +100) */
  clarity: number;
  /** Dehaze (-100 to +100) */
  dehaze: number;
  /** Vibrance (-100 to +100) */
  vibrance: number;
  /** Saturation (-100 to +100) */
  saturation: number;

  // â”€â”€ White balance â”€â”€
  /** Color temperature (2000-50000 Kelvin) */
  temperature: number;
  /** Tint (green-magenta, -150 to +150) */
  tint: number;

  // â”€â”€ Tone Curve â”€â”€
  /** Parametric tone curve points */
  tone_curve: ToneCurvePoint[];

  // â”€â”€ HSL / Color â”€â”€
  /** Per-color HSL adjustments */
  hsl: {
    red: HSLChannel;
    orange: HSLChannel;
    yellow: HSLChannel;
    green: HSLChannel;
    aqua: HSLChannel;
    blue: HSLChannel;
    purple: HSLChannel;
    magenta: HSLChannel;
  };

  // â”€â”€ Detail â”€â”€
  /** Sharpening amount (0-150) */
  sharpening: number;
  /** Sharpening radius (0.5-3.0) */
  sharpening_radius: number;
  /** luminance noise reduction (0-100) */
  noise_reduction_luminance: number;
  /** Color noise reduction (0-100) */
  noise_reduction_color: number;

  // â”€â”€ Lens Corrections â”€â”€
  /** Enable profile-based lens corrections */
  lens_correction_enabled: boolean;
  /** Vignette correction amount (0-200, 100=full) */
  vignette_correction: number;
  /** Distortion correction amount (0-200, 100=full) */
  distortion_correction: number;
}

// â”€â”€â”€ DEFAULTS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

export function createDefaultRecipe(name: string = 'Untitled'): EditRecipe {
  const defaultHSL: HSLChannel = { hue: 0, saturation: 0, luminance: 0 };
  return {
    name,
    description: 'Generated by SKYCRUNCHER Preset Developer',
    exposure: 0, contrast: 0, highlights: 0, shadows: 0,
    whites: 0, blacks: 0, texture: 0, clarity: 0, dehaze: 0,
    vibrance: 0, saturation: 0,
    temperature: 6500, tint: 0,
    tone_curve: [
      { x: 0, y: 0 }, { x: 64, y: 64 },
      { x: 128, y: 128 }, { x: 192, y: 192 },
      { x: 255, y: 255 },
    ],
    hsl: {
      red: { ...defaultHSL }, orange: { ...defaultHSL },
      yellow: { ...defaultHSL }, green: { ...defaultHSL },
      aqua: { ...defaultHSL }, blue: { ...defaultHSL },
      purple: { ...defaultHSL }, magenta: { ...defaultHSL },
    },
    sharpening: 40, sharpening_radius: 1.0,
    noise_reduction_luminance: 0, noise_reduction_color: 25,
    lens_correction_enabled: true,
    vignette_correction: 100, distortion_correction: 100,
  };
}

// â”€â”€â”€ XMP GENERATION â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

/**
 * Generate a valid Adobe Camera Raw .xmp preset file.
 *
 * This output can be:
 * 1. Saved as a .xmp file in the Lightroom presets folder
 * 2. Imported via Lightroom's "Import Presets" function
 * 3. Applied via Adobe Camera Raw
 */
export function generateXMP(recipe: EditRecipe): string {
  const toneCurveStr = recipe.tone_curve
    .map(p => `${p.x}, ${p.y}`)
    .join(', ');

  return `<?xpacket begin="\uFEFF" id="W5M0MpCehiHzreSzNTczkc9d"?>
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="SKYCRUNCHER Preset Developer">
  <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
    <rdf:Description
      xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"
      crs:PresetType="Normal"
      crs:Cluster=""
      crs:UUID="${generateUUID()}"
      crs:SupportsAmount="False"
      crs:SupportsColor="True"
      crs:SupportsMonochrome="True"
      crs:SupportsHighDynamicRange="True"
      crs:SupportsNormalDynamicRange="True"
      crs:SupportsSceneReferred="True"
      crs:SupportsOutputReferred="True"
      crs:CameraProfile="Adobe Standard"
      crs:Version="16.0"
      crs:ProcessVersion="15.4"
      crs:Name="${escapeXML(recipe.name)}"
      crs:Description="${escapeXML(recipe.description)}"
      crs:Exposure2012="${recipe.exposure.toFixed(2)}"
      crs:Contrast2012="${recipe.contrast}"
      crs:Highlights2012="${recipe.highlights}"
      crs:Shadows2012="${recipe.shadows}"
      crs:Whites2012="${recipe.whites}"
      crs:Blacks2012="${recipe.blacks}"
      crs:Texture="${recipe.texture}"
      crs:Clarity2012="${recipe.clarity}"
      crs:Dehaze="${recipe.dehaze}"
      crs:Vibrance="${recipe.vibrance}"
      crs:Saturation="${recipe.saturation}"
      crs:ColorTemperature="${recipe.temperature}"
      crs:Tint="${recipe.tint}"
      crs:Sharpness="${recipe.sharpening}"
      crs:SharpenRadius="${recipe.sharpening_radius.toFixed(1)}"
      crs:luminanceSmoothing="${recipe.noise_reduction_luminance}"
      crs:ColorNoiseReduction="${recipe.noise_reduction_color}"
      crs:LensProfileEnable="${recipe.lens_correction_enabled ? 1 : 0}"
      crs:LensManualDistortionAmount="${recipe.distortion_correction}"
      crs:VignetteAmount="${recipe.vignette_correction}"
      crs:HueAdjustmentRed="${recipe.hsl.red.hue}"
      crs:HueAdjustmentOrange="${recipe.hsl.orange.hue}"
      crs:HueAdjustmentYellow="${recipe.hsl.yellow.hue}"
      crs:HueAdjustmentGreen="${recipe.hsl.green.hue}"
      crs:HueAdjustmentAqua="${recipe.hsl.aqua.hue}"
      crs:HueAdjustmentBlue="${recipe.hsl.blue.hue}"
      crs:HueAdjustmentPurple="${recipe.hsl.purple.hue}"
      crs:HueAdjustmentMagenta="${recipe.hsl.magenta.hue}"
      crs:SaturationAdjustmentRed="${recipe.hsl.red.saturation}"
      crs:SaturationAdjustmentOrange="${recipe.hsl.orange.saturation}"
      crs:SaturationAdjustmentYellow="${recipe.hsl.yellow.saturation}"
      crs:SaturationAdjustmentGreen="${recipe.hsl.green.saturation}"
      crs:SaturationAdjustmentAqua="${recipe.hsl.aqua.saturation}"
      crs:SaturationAdjustmentBlue="${recipe.hsl.blue.saturation}"
      crs:SaturationAdjustmentPurple="${recipe.hsl.purple.saturation}"
      crs:SaturationAdjustmentMagenta="${recipe.hsl.magenta.saturation}"
      crs:luminanceAdjustmentRed="${recipe.hsl.red.luminance}"
      crs:luminanceAdjustmentOrange="${recipe.hsl.orange.luminance}"
      crs:luminanceAdjustmentYellow="${recipe.hsl.yellow.luminance}"
      crs:luminanceAdjustmentGreen="${recipe.hsl.green.luminance}"
      crs:luminanceAdjustmentAqua="${recipe.hsl.aqua.luminance}"
      crs:luminanceAdjustmentBlue="${recipe.hsl.blue.luminance}"
      crs:luminanceAdjustmentPurple="${recipe.hsl.purple.luminance}"
      crs:luminanceAdjustmentMagenta="${recipe.hsl.magenta.luminance}"
      crs:ToneCurveName2012="Custom">
      <crs:ToneCurve>
        <rdf:Seq>
${recipe.tone_curve.map(p => `          <rdf:li>${p.x}, ${p.y}</rdf:li>`).join('\n')}
        </rdf:Seq>
      </crs:ToneCurve>
    </rdf:Description>
  </rdf:RDF>
</x:xmpmeta>
<?xpacket end="w"?>`;
}

// â”€â”€â”€ HELPERS â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€

function escapeXML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function generateUUID(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
    const r = Math.random() * 16 | 0;
    const v = c === 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

