//! M3 GATE — decision identity of the Rust verifier against the TS oracle
//! (quad_verify_model.ts, executed via esbuild in crates/conformance/verify_oracle/).
//!
//! For EVERY fixture: all integer fields bit-equal (besti, nMatched, nDistractor,
//! nConflict, nTest, nRef, bailedAt, stoppedAt); floats (logOdds, bestWorst, finalOdds,
//! effArea) within 1e-9 relative with a 1e-9 absolute floor. Any integer divergence is a
//! SEMANTICS BUG in the port — fix the port, never the tolerance.
//!
//! Fixtures are generated by crates/conformance/verify_oracle/gen_fixtures.mjs
//! (deterministic; oracle output embedded as `expected`).

use std::fs;
use std::path::{Path, PathBuf};

use serde_json::Value;
use solver_core::verify::{
    compute_quad_verify, verify_with_seed_exclusion, QuadAnchor, VerifyOpts, VerifyResult,
    VerifyWorkspace,
};

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("fixtures").join("verify")
}

fn f(v: &Value, k: &str) -> f64 {
    v[k].as_f64().unwrap_or_else(|| panic!("missing/non-f64 field {k}"))
}
fn int(v: &Value, k: &str) -> i64 {
    v[k].as_i64().unwrap_or_else(|| panic!("missing/non-int field {k}"))
}

/// INPUT floats travel as IEEE-754 bit-pattern hex (`…Bits` fields) — serde_json's
/// DEFAULT decimal parse is NOT correctly rounded in this workspace (float_roundtrip
/// off; M2 lane finding), and a 1-ulp input skew can flip a boundary comparison into
/// an integer divergence. Bits are REQUIRED here: no silent decimal fallback.
fn bits(v: &Value) -> f64 {
    let s = v.as_str().unwrap_or_else(|| panic!("expected f64 bits hex string, got {v}"));
    f64::from_bits(u64::from_str_radix(s, 16).unwrap_or_else(|e| panic!("bad bits {s}: {e}")))
}

fn parse_opts(v: &Value, b: &Value) -> VerifyOpts {
    VerifyOpts {
        verify_pix_sigma: bits(&b["verifyPixSigma"]),
        distractor: bits(&b["distractor"]),
        max_match_sigma: bits(&b["maxMatchSigma"]),
        do_gamma: v["doGamma"].as_bool().unwrap(),
        do_ror: v["doRoR"].as_bool().unwrap(),
        eff_area_grid_n: v["effAreaGridN"].as_u64().unwrap() as u32,
        log_bail: bits(&b["logBail"]),
        // null encodes +Infinity (JSON cannot carry it)
        log_stop: if b["logStop"].is_null() { f64::INFINITY } else { bits(&b["logStop"]) },
    }
}

fn parse_refs(v: &Value) -> Vec<[f64; 2]> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|r| [bits(&r[0]), bits(&r[1])])
        .collect()
}
fn parse_tests(v: &Value) -> Vec<(f64, f64, f64)> {
    v.as_array()
        .unwrap()
        .iter()
        .map(|t| (bits(&t[0]), bits(&t[1]), bits(&t[2])))
        .collect()
}

fn run_fixture(fx: &Value, ws: &mut VerifyWorkspace) -> VerifyResult {
    let opts = parse_opts(&fx["opts"], &fx["optsBits"]);
    let refs = parse_refs(&fx["refsBits"]);
    let tests = parse_tests(&fx["testsBits"]);
    let (w, h) = (bits(&fx["wBits"]), bits(&fx["hBits"]));
    match fx["kind"].as_str().unwrap() {
        "core" => {
            let q = &fx["quadBits"];
            let quad =
                QuadAnchor { cx: bits(&q["cx"]), cy: bits(&q["cy"]), quad_r2: bits(&q["quadR2"]) };
            compute_quad_verify(&refs, &tests, w, h, quad, &opts, ws)
        }
        "composed" => {
            let sr: Vec<usize> = fx["seedRefIndices"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_u64().unwrap() as usize)
                .collect();
            let st: Vec<usize> = fx["seedTestIndices"]
                .as_array()
                .unwrap()
                .iter()
                .map(|x| x.as_u64().unwrap() as usize)
                .collect();
            let det_a = [bits(&fx["detABits"][0]), bits(&fx["detABits"][1])];
            let det_b = [bits(&fx["detBBits"][0]), bits(&fx["detBBits"][1])];
            verify_with_seed_exclusion(
                &refs,
                [sr[0], sr[1], sr[2], sr[3]],
                &tests,
                [st[0], st[1], st[2], st[3]],
                det_a,
                det_b,
                w,
                h,
                &opts,
                ws,
            )
        }
        k => panic!("unknown fixture kind {k}"),
    }
}

/// 1e-9 relative, 1e-9 absolute floor. Returns the observed relative deviation.
fn float_check(name: &str, field: &str, got: f64, want: f64, failures: &mut Vec<String>) -> f64 {
    let scale = got.abs().max(want.abs());
    let tol = 1e-9_f64.max(1e-9 * scale);
    let dev = (got - want).abs();
    if !(dev <= tol) {
        failures.push(format!("{name}: FLOAT {field} got={got:?} want={want:?} dev={dev:e}"));
    }
    if scale > 0.0 { dev / scale } else { dev }
}

fn int_check(name: &str, field: &str, got: i64, want: i64, failures: &mut Vec<String>) {
    if got != want {
        failures.push(format!(
            "{name}: INTEGER {field} got={got} want={want} — semantics bug in the port"
        ));
    }
}

/// Runs every fixture whose name matches `pred`; asserts decision identity.
fn run_group(group: &str, pred: impl Fn(&str) -> bool, min_count: usize) {
    let dir = fixtures_dir();
    let mut names: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("fixtures dir {dir:?}: {e} — run gen_fixtures.mjs first"))
        .map(|e| e.unwrap().path())
        .filter(|p| {
            p.extension().is_some_and(|x| x == "json")
                && p.file_stem().is_some_and(|s| s != "MANIFEST")
        })
        .collect();
    names.sort();

    let mut ws = VerifyWorkspace::new(); // ONE workspace across the whole group (reuse proof)
    let mut failures: Vec<String> = Vec::new();
    let mut count = 0usize;
    let mut max_rel_dev: f64 = 0.0;
    let mut max_rel_at = String::new();

    for path in &names {
        let fx: Value = serde_json::from_str(&fs::read_to_string(path).unwrap()).unwrap();
        let name = fx["name"].as_str().unwrap().to_string();
        if !pred(&name) {
            continue;
        }
        count += 1;
        let got = run_fixture(&fx, &mut ws);
        let e = &fx["expected"];

        int_check(&name, "besti", got.besti, int(e, "besti"), &mut failures);
        int_check(&name, "nMatched", got.n_matched as i64, int(e, "nMatched"), &mut failures);
        int_check(&name, "nDistractor", got.n_distractor as i64, int(e, "nDistractor"), &mut failures);
        int_check(&name, "nConflict", got.n_conflict as i64, int(e, "nConflict"), &mut failures);
        int_check(&name, "nTest", got.n_test as i64, int(e, "nTest"), &mut failures);
        int_check(&name, "nRef", got.n_ref as i64, int(e, "nRef"), &mut failures);
        int_check(&name, "bailedAt", got.bailed_at, int(e, "bailedAt"), &mut failures);
        int_check(&name, "stoppedAt", got.stopped_at, int(e, "stoppedAt"), &mut failures);

        for (field, g, w) in [
            ("logOdds", got.log_odds, f(e, "logOdds")),
            ("bestWorst", got.best_worst, f(e, "bestWorst")),
            ("finalOdds", got.final_odds, f(e, "finalOdds")),
            ("effArea", got.eff_area, f(e, "effArea")),
        ] {
            let rel = float_check(&name, field, g, w, &mut failures);
            if rel > max_rel_dev {
                max_rel_dev = rel;
                max_rel_at = format!("{name}.{field}");
            }
        }
    }

    assert!(
        count >= min_count,
        "{group}: only {count} fixtures found (need >= {min_count}) — run gen_fixtures.mjs"
    );
    eprintln!(
        "[m3 identity] group={group} fixtures={count} max_rel_float_dev={max_rel_dev:e} at {max_rel_at}"
    );
    assert!(
        failures.is_empty(),
        "{group}: {} divergence(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn m3_identity_synthetic() {
    run_group("synthetic", |n| n.starts_with("syn_"), 16);
}

#[test]
fn m3_identity_real() {
    run_group("real", |n| n.starts_with("real_"), 11);
}

#[test]
fn m3_identity_composed() {
    run_group("composed", |n| n.starts_with("comp_"), 4);
}

/// The full set must be present (~25+ cases) — guards against a silently empty dir.
#[test]
fn m3_identity_fixture_census() {
    let dir = fixtures_dir();
    let n = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("fixtures dir {dir:?}: {e} — run gen_fixtures.mjs first"))
        .filter(|e| {
            let p = e.as_ref().unwrap().path();
            p.extension().is_some_and(|x| x == "json")
                && p.file_stem().is_some_and(|s| s != "MANIFEST")
        })
        .count();
    assert!(n >= 25, "expected >= 25 fixtures, found {n}");
}

/// Workspace reuse must not perturb decisions: fixture -> other fixture -> fixture again,
/// same workspace; first and third runs bit-identical on every field.
#[test]
fn m3_identity_workspace_reuse_bit_exact() {
    let dir = fixtures_dir();
    let a: Value = serde_json::from_str(
        &fs::read_to_string(dir.join("real_truth.json")).unwrap(),
    )
    .unwrap();
    let b: Value = serde_json::from_str(
        &fs::read_to_string(dir.join("comp_real_truth.json")).unwrap(),
    )
    .unwrap();
    let mut ws = VerifyWorkspace::new();
    let r1 = run_fixture(&a, &mut ws);
    let _ = run_fixture(&b, &mut ws);
    let r3 = run_fixture(&a, &mut ws);
    assert!(
        r1.log_odds.to_bits() == r3.log_odds.to_bits()
            && r1.best_worst.to_bits() == r3.best_worst.to_bits()
            && r1.final_odds.to_bits() == r3.final_odds.to_bits()
            && r1.eff_area.to_bits() == r3.eff_area.to_bits()
            && r1.besti == r3.besti
            && r1.n_matched == r3.n_matched
            && r1.n_distractor == r3.n_distractor
            && r1.n_conflict == r3.n_conflict
            && r1.n_test == r3.n_test
            && r1.n_ref == r3.n_ref
            && r1.bailed_at == r3.bailed_at
            && r1.stopped_at == r3.stopped_at,
        "workspace reuse changed a result"
    );
}
