// Vitest global setup — mocks native-only modules that can't run in Node.js
// This file is referenced via vite.config.ts test.setupFiles

import { vi } from 'vitest';

// ─── Mock wasm_compute ──────────────────────────────────────────────────────
// The WASM binary is generated by wasm-pack and only available in the browser
// or when loaded via a WASM-capable environment. In Vitest's default Node.js
// environment the binary is not initialized, so every wasm.* call throws.
// We provide a pure-JS reference implementation of the numerical functions
// so that TypeScript unit tests can run without loading the .wasm file.

vi.mock('../wasm_compute/pkg/wasm_compute', async () => {
    const DEG2RAD = Math.PI / 180;
    const RAD2DEG = 180 / Math.PI;

    // ── Kepler solver helpers ──────────────────────────────────────────────────

    /** Solve Kepler's equation E - e*sin(E) = M via Newton-Raphson */
    function solveKeplerEq(M: number, e: number): number {
        let E = M;
        for (let i = 0; i < 50; i++) {
            const dE = (M - E + e * Math.sin(E)) / (1 - e * Math.cos(E));
            E += dE;
            if (Math.abs(dE) < 1e-10) break;
        }
        return E;
    }

    /**
     * Minimal Keplerian orbit solver — returns heliocentric ecliptic (AU).
     * Arguments match the Rust wasm.OrbitalElements(N, i, w, a, e, M)
     */
    class OrbitalElements {
        N: number; i: number; w: number; a: number; e: number; M: number;
        constructor(N: number, i: number, w: number, a: number, e: number, M: number) {
            this.N = N * DEG2RAD;
            this.i = i * DEG2RAD;
            this.w = w * DEG2RAD;
            this.a = a;
            this.e = e;
            this.M = M * DEG2RAD;
        }
        free() {}
    }

    class Vec3Result {
        x: number; y: number; z: number;
        constructor(x: number, y: number, z: number) { this.x = x; this.y = y; this.z = z; }
        free() {}
    }

    function solve_kepler(el: OrbitalElements, _d: number): Vec3Result {
        const E = solveKeplerEq(el.M, el.e);
        const xv = el.a * (Math.cos(E) - el.e);
        const yv = el.a * Math.sqrt(1 - el.e * el.e) * Math.sin(E);
        const v = Math.atan2(yv, xv);
        const r = Math.sqrt(xv * xv + yv * yv);
        const cosN = Math.cos(el.N), sinN = Math.sin(el.N);
        const cosI = Math.cos(el.i), sinI = Math.sin(el.i);
        const cosVW = Math.cos(v + el.w), sinVW = Math.sin(v + el.w);
        const x = r * (cosN * cosVW - sinN * sinVW * cosI);
        const y = r * (sinN * cosVW + cosN * sinVW * cosI);
        const z = r * sinVW * sinI;
        return new Vec3Result(x, y, z);
    }

    // Tiny topocentric correction stub — returns [ra, dec] nearly unchanged
    function apply_topocentric_correction(
        ra: number, dec: number, _distAu: number, _lat: number, _lon: number, _d: number
    ): Float64Array {
        return new Float64Array([ra, dec]);
    }

    return {
        // Centered 4-DOF CD-matrix least-squares fit — faithful port of
        // sky_transform.rs::fit_wcs_bulk → [cd11, cd12, cd21, cd22] (empty on degenerate)
        fit_wcs_bulk(
            pixelX: Float64Array, pixelY: Float64Array,
            skyXi: Float64Array, skyEta: Float64Array,
            crpixX: number, crpixY: number
        ): Float64Array {
            const n = pixelX.length;
            if (n < 3) return new Float64Array(0);
            let sDx2 = 0, sDy2 = 0, sDxDy = 0, sDxXi = 0, sDyXi = 0, sDxEta = 0, sDyEta = 0;
            for (let i = 0; i < n; i++) {
                const dx = pixelX[i] - crpixX;
                const dy = pixelY[i] - crpixY;
                sDx2 += dx * dx; sDy2 += dy * dy; sDxDy += dx * dy;
                sDxXi += dx * skyXi[i]; sDyXi += dy * skyXi[i];
                sDxEta += dx * skyEta[i]; sDyEta += dy * skyEta[i];
            }
            const det = sDx2 * sDy2 - sDxDy * sDxDy;
            if (Math.abs(det) < 1e-20) return new Float64Array(0);
            return new Float64Array([
                (sDy2 * sDxXi - sDxDy * sDyXi) / det,
                (sDx2 * sDyXi - sDxDy * sDxXi) / det,
                (sDy2 * sDxEta - sDxDy * sDyEta) / det,
                (sDx2 * sDyEta - sDxDy * sDxEta) / det,
            ]);
        },

        // Haversine angular separation (rad → rad → rad)
        calculate_angular_separation(ra1: number, dec1: number, ra2: number, dec2: number): number {
            const dDec = dec2 - dec1;
            const dRa = ra2 - ra1;
            const a = Math.sin(dDec / 2) ** 2 +
                      Math.cos(dec1) * Math.cos(dec2) * Math.sin(dRa / 2) ** 2;
            return 2 * Math.asin(Math.sqrt(a));
        },

        // Standard Gnomonic projection  →  [xi_rad, eta_rad]
        gnomonic_project(raRad: number, decRad: number, ra0Rad: number, dec0Rad: number): Float64Array {
            const dRa = raRad - ra0Rad;
            const cosD0 = Math.cos(dec0Rad);
            const sinD0 = Math.sin(dec0Rad);
            const cosD  = Math.cos(decRad);
            const sinD  = Math.sin(decRad);
            const cosdRa = Math.cos(dRa);
            const denom  = sinD0 * sinD + cosD0 * cosD * cosdRa;
            if (denom <= 0) return new Float64Array([NaN, NaN]);
            const xi  = cosD * Math.sin(dRa) / denom;
            const eta = (cosD0 * sinD - sinD0 * cosD * cosdRa) / denom;
            return new Float64Array([xi, eta]);
        },

        // Inverse Gnomonic  →  [ra_rad, dec_rad]
        inverse_gnomonic(xiRad: number, etaRad: number, ra0Rad: number, dec0Rad: number): Float64Array {
            const r     = Math.sqrt(xiRad ** 2 + etaRad ** 2);
            const c     = Math.atan(r);
            const cosC  = Math.cos(c);
            const sinC  = Math.sin(c);
            const sinD0 = Math.sin(dec0Rad);
            const cosD0 = Math.cos(dec0Rad);
            const decRad = Math.asin(cosC * sinD0 + (etaRad * sinC * cosD0) / (r || 1e-15));
            const raRad  = ra0Rad + Math.atan2(xiRad * sinC, r * cosD0 * cosC - etaRad * sinD0 * sinC);
            return new Float64Array([raRad, decRad]);
        },

        // CD matrix  →  [cd11, cd12, cd21, cd22] in radians/pixel
        // RECONCILED to the compiled Rust (src/engine/wasm_compute/src/sky_transform.rs
        // calculate_cd_matrix, lines 127-142):
        //   CD1_1 = +s·cos(rot)          CD1_2 = -s·sin(rot)
        //   CD2_1 = -s·sin(rot)·parity   CD2_2 = -s·cos(rot)·parity
        // This mock previously encoded the NEGATED convention ([-p·s·cos, +p·s·sin,
        // s·sin, s·cos]), which the real solver never produces — a latent trap that
        // would have regression-locked a wrong matrix. The real artifact is asserted
        // directly in wasm_core.test.ts; this keeps the mock a faithful stand-in.
        calculate_cd_matrix(scaleArcsec: number, rotDeg: number, parity: number): Float64Array {
            const scaleRad = (scaleArcsec / 3600) * DEG2RAD;
            const rotRad = rotDeg * DEG2RAD;
            const cos = Math.cos(rotRad), sin = Math.sin(rotRad);
            return new Float64Array([
                 scaleRad * cos,          -scaleRad * sin,
                -scaleRad * sin * parity, -scaleRad * cos * parity,
            ]);
        },

        // Pixel scale from CD matrix (arcsec/px)
        // RECONCILED to Rust (sky_transform.rs pixel_scale_from_cd, lines 144-150):
        // the MEAN of the two CD column norms — NOT sqrt(|det|). The two agree only
        // for an orthogonal, equal-scale CD; they diverge for sheared/unequal CDs.
        pixel_scale_from_cd(cd11: number, cd12: number, cd21: number, cd22: number): number {
            const scale1 = Math.sqrt(cd11 ** 2 + cd21 ** 2) * RAD2DEG * 3600;
            const scale2 = Math.sqrt(cd12 ** 2 + cd22 ** 2) * RAD2DEG * 3600;
            return (scale1 + scale2) / 2;
        },

        // Rotation from CD matrix (degrees)
        rotation_from_cd(cd11: number, cd12: number): number {
            return Math.atan2(cd12, cd11) * RAD2DEG;
        },


        // Bulk sky conversion stub (returns empty array — not tested in unit tests)
        wcs_pixels_to_sky_bulk(_xy: Float64Array): Float64Array {
            return new Float64Array(0);
        },

        // EphemerisEngine needs: OrbitalElements class, solve_kepler, apply_topocentric_correction
        OrbitalElements,
        solve_kepler,
        apply_topocentric_correction,

        batch_solve_ephemeris(bodies: any[], lat: number, lon: number, d: number, _jd: number) {
            return bodies.filter(b => b.id !== 'earth').map(b => {
                const el = new OrbitalElements(b.n, b.i, b.w, b.a, b.e, b.m);
                const pos = solve_kepler(el, d);
                
                // Very crude equatorial conversion for mock
                const dist_au = Math.sqrt(pos.x**2 + pos.y**2 + pos.z**2);
                const ra = Math.atan2(pos.y, pos.x) * RAD2DEG / 15;
                const dec = Math.atan2(pos.z, Math.sqrt(pos.x**2 + pos.y**2)) * RAD2DEG;
                
                return {
                    id: b.id,
                    ra: ra < 0 ? ra + 24 : ra,
                    dec: dec,
                    alt: 10, // Mock altitude above horizon
                    az: 180,
                    mag: b.mag_base || 10,
                    dist_au: dist_au,
                    radius_arcsec: 5
                };
            });
        }
    };
});
